// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/guide": {
    params: {};
  };
  "/inquiries": {
    params: {};
  };
  "/reservation": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/guide" | "/inquiries" | "/reservation";
  };
  "./components/Scaffold.tsx": {
    id: "components/Scaffold";
    page: "/" | "/guide" | "/inquiries" | "/reservation";
  };
  "./pages/Index.tsx": {
    id: "pages/Index";
    page: "/";
  };
  "./pages/Guide.tsx": {
    id: "pages/Guide";
    page: "/guide";
  };
  "./pages/Inquiries.tsx": {
    id: "pages/Inquiries";
    page: "/inquiries";
  };
  "./pages/Reservation.tsx": {
    id: "pages/Reservation";
    page: "/reservation";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "components/Scaffold": typeof import("./app/./components/Scaffold.tsx");
  "pages/Index": typeof import("./app/./pages/Index.tsx");
  "pages/Guide": typeof import("./app/./pages/Guide.tsx");
  "pages/Inquiries": typeof import("./app/./pages/Inquiries.tsx");
  "pages/Reservation": typeof import("./app/./pages/Reservation.tsx");
};