// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/guide": {
    params: {};
  };
  "/inquiries": {
    params: {};
  };
  "/reservation": {
    params: {};
  };
  "/reservation/login": {
    params: {};
  };
  "/reservation/:bookingId": {
    params: {
      "bookingId": string;
    };
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/my": {
    params: {};
  };
  "/terms-of-service": {
    params: {};
  };
  "/booking/:bookingId/recording": {
    params: {
      "bookingId": string;
    };
  };
  "/join/:groupId": {
    params: {
      "groupId": string;
    };
  };
  "/admin": {
    params: {};
  };
  "/admin/pending-bookings": {
    params: {};
  };
  "/admin/pending-refunds": {
    params: {};
  };
  "/admin/groups": {
    params: {};
  };
  "/admin/users": {
    params: {};
  };
  "/admin/reservations": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/guide" | "/inquiries" | "/reservation" | "/reservation/login" | "/reservation/:bookingId" | "/login" | "/register" | "/my" | "/terms-of-service" | "/booking/:bookingId/recording" | "/join/:groupId" | "/admin" | "/admin/pending-bookings" | "/admin/pending-refunds" | "/admin/groups" | "/admin/users" | "/admin/reservations";
  };
  "./components/Scaffold.tsx": {
    id: "components/Scaffold";
    page: "/" | "/guide" | "/inquiries" | "/reservation" | "/reservation/login" | "/reservation/:bookingId" | "/login" | "/register" | "/my" | "/terms-of-service";
  };
  "./pages/Index.tsx": {
    id: "pages/Index";
    page: "/";
  };
  "./pages/Guide.tsx": {
    id: "pages/Guide";
    page: "/guide";
  };
  "./pages/Inquiries.tsx": {
    id: "pages/Inquiries";
    page: "/inquiries";
  };
  "./pages/Reservation/Create.tsx": {
    id: "pages/Reservation/Create";
    page: "/reservation";
  };
  "./pages/Reservation/Login.tsx": {
    id: "pages/Reservation/Login";
    page: "/reservation/login";
  };
  "./pages/Reservation/Show.tsx": {
    id: "pages/Reservation/Show";
    page: "/reservation/:bookingId";
  };
  "./pages/Login.tsx": {
    id: "pages/Login";
    page: "/login";
  };
  "./pages/Register.tsx": {
    id: "pages/Register";
    page: "/register";
  };
  "./pages/MyPage.tsx": {
    id: "pages/MyPage";
    page: "/my";
  };
  "./pages/legal/TermsOfService.tsx": {
    id: "pages/legal/TermsOfService";
    page: "/terms-of-service";
  };
  "./pages/Recording.tsx": {
    id: "pages/Recording";
    page: "/booking/:bookingId/recording";
  };
  "./pages/JoinGroup.tsx": {
    id: "pages/JoinGroup";
    page: "/join/:groupId";
  };
  "./components/AdminScaffold.tsx": {
    id: "components/AdminScaffold";
    page: "/admin" | "/admin/pending-bookings" | "/admin/pending-refunds" | "/admin/groups" | "/admin/users" | "/admin/reservations";
  };
  "./pages/Admin/ConfirmedBookings.tsx": {
    id: "pages/Admin/ConfirmedBookings";
    page: "/admin";
  };
  "./pages/Admin/PendingBookings.tsx": {
    id: "pages/Admin/PendingBookings";
    page: "/admin/pending-bookings";
  };
  "./pages/Admin/RefundPendingBookings.tsx": {
    id: "pages/Admin/RefundPendingBookings";
    page: "/admin/pending-refunds";
  };
  "./pages/Admin/Groups.tsx": {
    id: "pages/Admin/Groups";
    page: "/admin/groups";
  };
  "./pages/Admin/Users.tsx": {
    id: "pages/Admin/Users";
    page: "/admin/users";
  };
  "./pages/Admin/Reservations.tsx": {
    id: "pages/Admin/Reservations";
    page: "/admin/reservations";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "components/Scaffold": typeof import("./app/./components/Scaffold.tsx");
  "pages/Index": typeof import("./app/./pages/Index.tsx");
  "pages/Guide": typeof import("./app/./pages/Guide.tsx");
  "pages/Inquiries": typeof import("./app/./pages/Inquiries.tsx");
  "pages/Reservation/Create": typeof import("./app/./pages/Reservation/Create.tsx");
  "pages/Reservation/Login": typeof import("./app/./pages/Reservation/Login.tsx");
  "pages/Reservation/Show": typeof import("./app/./pages/Reservation/Show.tsx");
  "pages/Login": typeof import("./app/./pages/Login.tsx");
  "pages/Register": typeof import("./app/./pages/Register.tsx");
  "pages/MyPage": typeof import("./app/./pages/MyPage.tsx");
  "pages/legal/TermsOfService": typeof import("./app/./pages/legal/TermsOfService.tsx");
  "pages/Recording": typeof import("./app/./pages/Recording.tsx");
  "pages/JoinGroup": typeof import("./app/./pages/JoinGroup.tsx");
  "components/AdminScaffold": typeof import("./app/./components/AdminScaffold.tsx");
  "pages/Admin/ConfirmedBookings": typeof import("./app/./pages/Admin/ConfirmedBookings.tsx");
  "pages/Admin/PendingBookings": typeof import("./app/./pages/Admin/PendingBookings.tsx");
  "pages/Admin/RefundPendingBookings": typeof import("./app/./pages/Admin/RefundPendingBookings.tsx");
  "pages/Admin/Groups": typeof import("./app/./pages/Admin/Groups.tsx");
  "pages/Admin/Users": typeof import("./app/./pages/Admin/Users.tsx");
  "pages/Admin/Reservations": typeof import("./app/./pages/Admin/Reservations.tsx");
};